---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-fpm
  labels:
    app.kubernetes.io/name: microblog-fpm
    app.kubernetes.io/component: fpm
    app.kubernetes.io/part-of: microblog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-fpm
      app.kubernetes.io/component: fpm
      app.kubernetes.io/part-of: microblog
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-fpm
        app.kubernetes.io/component: fpm
        app.kubernetes.io/part-of: microblog
    spec:
      containers:
        - name: microblog-fpm
          image: registry.digitalocean.com/shark-fyi/microblog-php:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: dot-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true
          # resources:
          #   requests:
          #     memory: 250Mi
          #     cpu: 250m
      volumes:
        - name: dot-env
          secret:
            secretName: microblog

      imagePullSecrets:
        - name: registry-shark-fyi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-nginx
  labels:
    app.kubernetes.io/name: microblog-nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: microblog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-nginx
      app.kubernetes.io/component: nginx
      app.kubernetes.io/part-of: microblog
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-nginx
        app.kubernetes.io/component: nginx
        app.kubernetes.io/part-of: microblog
    spec:
      containers:
        - name: microblog-nginx
          image: registry.digitalocean.com/shark-fyi/microblog-nginx:latest
          ports:
            - containerPort: 80
          # resources:
          #   requests:
          #     memory: 250Mi
          #     cpu: 250m
          livenessProbe:
            httpGet:
              path: /healthz/nginx
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz/laravel
              port: 80
      imagePullSecrets:
        - name: registry-shark-fyi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-horizon
  labels:
    app.kubernetes.io/name: microblog-horizon
    app.kubernetes.io/component: horizon
    app.kubernetes.io/part-of: microblog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-horizon
      app.kubernetes.io/component: horizon
      app.kubernetes.io/part-of: microblog
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-horizon
        app.kubernetes.io/component: horizon
        app.kubernetes.io/part-of: microblog
    spec:
      containers:
        - name: microblog-horizon
          image: registry.digitalocean.com/shark-fyi/microblog-php:latest
          command:
            - php
            - artisan
            - horizon
          volumeMounts:
            - name: dot-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true
          # resources:
          #   requests:
          #     memory: 250Mi
          #     cpu: 250m
      volumes:
        - name: dot-env
          secret:
            secretName: microblog

      imagePullSecrets:
        - name: registry-shark-fyi

---
apiVersion: v1
kind: Service
metadata:
  name: microblog-fpm
spec:
  selector:
    app.kubernetes.io/name: microblog-fpm
    app.kubernetes.io/component: fpm
    app.kubernetes.io/part-of: microblog
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: microblog-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz/laravel"
spec:
  selector:
    app.kubernetes.io/name: microblog-nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: microblog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
