---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-nginx
  labels:
    app.kubernetes.io/name: microblog-nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: microblog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-nginx
      app.kubernetes.io/component: nginx
      app.kubernetes.io/part-of: microblog
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-nginx
        app.kubernetes.io/component: nginx
        app.kubernetes.io/part-of: microblog
    spec:
      containers:
        - name: nginx
          image: kamaln7/microblog-nginx:1.0.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz/nginx
              port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-fpm
  labels:
    app.kubernetes.io/name: microblog-fpm
    app.kubernetes.io/component: fpm
    app.kubernetes.io/part-of: microblog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-fpm
      app.kubernetes.io/component: fpm
      app.kubernetes.io/part-of: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-fpm
        app.kubernetes.io/component: fpm
        app.kubernetes.io/part-of: microblog
    spec:
      containers:
        - name: fpm
          image: kamaln7/microblog-php:1.0.0
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: dot-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: dot-env
          secret:
            secretName: microblog

---
apiVersion: v1
kind: Service
metadata:
  name: microblog-fpm
spec:
  selector:
    app.kubernetes.io/name: microblog-fpm
    app.kubernetes.io/component: fpm
    app.kubernetes.io/part-of: microblog
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: microblog-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz/nginx"
    service.beta.kubernetes.io/do-loadbalancer-http2-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "d20a66d1-35af-4bc8-95c9-e4621d88cc18"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "example.com"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  selector:
    app.kubernetes.io/name: microblog-nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: microblog
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http2
      protocol: TCP
      port: 443
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-horizon
  labels:
    app.kubernetes.io/name: microblog-horizon
    app.kubernetes.io/component: horizon
    app.kubernetes.io/part-of: microblog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-horizon
      app.kubernetes.io/component: horizon
      app.kubernetes.io/part-of: microblog
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-horizon
        app.kubernetes.io/component: horizon
        app.kubernetes.io/part-of: microblog
    spec:
      containers:
        - name: horizon
          image: kamaln7/microblog-php:1.0.0
          command:
            - php
            - artisan
            - horizon
          volumeMounts:
            - name: dot-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: dot-env
          secret:
            secretName: microblog

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: microblog-scheduler
  labels:
    app.kubernetes.io/name: microblog-scheduler
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: microblog
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-scheduler
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/part-of: microblog
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: scheduler
              image: kamaln7/microblog-php:1.0.0
              command:
                - php
                - artisan
                - schedule:run
              volumeMounts:
                - name: dot-env
                  mountPath: /app/.env
                  subPath: .env
                  readOnly: true
          volumes:
            - name: dot-env
              secret:
                secretName: microblog
