---
apiVersion: v1
kind: Pod
metadata:
  name: microblog-migrate
  labels:
    app.kubernetes.io/name: microblog-migrate
    app.kubernetes.io/component: migrate
    app.kubernetes.io/part-of: microblog
spec:
  restartPolicy: Never
  containers:
    - name: migrate
      image: kamaln7/microblog-php:latest
      command:
        - php
        - artisan
        - migrate
        - --force
      volumeMounts:
        - name: dot-env
          mountPath: /app/.env
          subPath: .env
          readOnly: true
  volumes:
    - name: dot-env
      secret:
        secretName: microblog
